<a href="https://colab.research.google.com/github/aruntakhur/NWP/blob/main/NWP_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [4]:
a.dtype

dtype('int64')

In [5]:
type(a)

numpy.ndarray

In [6]:
b = np.array([1.2, 3.5, 5.1])

In [7]:
b.dtype

dtype('float64')

In [8]:
a = np.zeros((3, 4))

In [9]:
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [12]:
np.linspace(0, 2, 9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
from numpy import pi
x = np.linspace(0, 2 * pi, 100) 
f = np.sin(x)

In [14]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [15]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [17]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a-b
c

array([20, 29, 38, 47])

In [18]:
a = np.array([20, 30, 40, 50])
b = np.array([2])
c = a-b
c

array([18, 28, 38, 48])

In [19]:
c*10

array([180, 280, 380, 480])

In [20]:
c**2

array([ 324,  784, 1444, 2304])

In [21]:
A = np.array([[1, 1],
...           [0, 1]])
B = np.array([[2, 0],
...           [3, 4]])

In [22]:
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [23]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [24]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [25]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [27]:
b.sum(axis=1) 

array([ 6, 22, 38])

In [28]:
b.min(axis=0) 

array([0, 1, 2, 3])

In [29]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [30]:
a[2:5]

array([ 8, 27, 64])

In [31]:
a[::-1]  # reversed a

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [32]:
b = np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [33]:
b[0:5, 1]  # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [34]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [35]:
b[:, 1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [36]:
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [37]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([40, 41, 42, 43])

In [38]:
c = np.array([[[  0,  1,  2],  # a 3D array (two stacked 2D arrays)
...                [ 10, 12, 13]],
...               [[100, 101, 102],
...                [110, 112, 113]]])

In [39]:
c[1, :, :]

array([[100, 101, 102],
       [110, 112, 113]])

In [40]:
for row in b:
...     print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [41]:
for element in b.flat:    #each element
...     print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [42]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [45]:
b.reshape(2, 10)

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [46]:
b.T 

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [48]:
b.resize((2, 10))

In [50]:
b.shape

(2, 10)

In [56]:
b.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [60]:
a = np.random.rand(3,2)*10 #random samples from a uniform distribution over [0, 1).
a

array([[1.25218733, 4.3761123 ],
       [6.23513507, 4.3688997 ],
       [8.92571464, 1.67314177]])

In [62]:
b = np.random.rand(3,2)*10 #random samples from a uniform distribution over [0, 1).
b

array([[6.32527004, 4.69628761],
       [2.56780115, 8.99360849],
       [8.41796223, 7.53777549]])

In [63]:
np.vstack((a, b))

array([[1.25218733, 4.3761123 ],
       [6.23513507, 4.3688997 ],
       [8.92571464, 1.67314177],
       [6.32527004, 4.69628761],
       [2.56780115, 8.99360849],
       [8.41796223, 7.53777549]])

In [64]:
np.hstack((a, b))

array([[1.25218733, 4.3761123 , 6.32527004, 4.69628761],
       [6.23513507, 4.3688997 , 2.56780115, 8.99360849],
       [8.92571464, 1.67314177, 8.41796223, 7.53777549]])

In [65]:
a = np.array([[ 0,  1,  2,  3],
...               [ 4,  5,  6,  7],
...               [ 8,  9, 10, 11]])
b=a                                   # no new object is created
b[1,1]=55
print(b)
print(a)

[[ 0  1  2  3]
 [ 4 55  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4 55  6  7]
 [ 8  9 10 11]]


In [69]:
a = np.arange(12).reshape(3, 4)
print(a)
b = a > 4
b  # `b` is a boolean with `a`'s shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [68]:
a[b] = 0  # All elements of `a` higher than 4 become 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
import pandas as pd

In [72]:
url = 'https://github.com/aruntakhur/NWP/blob/main/music.csv'
pd.read_csv(url)

ParserError: ignored